name: Update Downloads

on:
  release:
    types: [published]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  check-repository-and-update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Get repository details and validate
        id: repo_info
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F'/' '{print $1"/"$2}')
          if [ "$REPO_NAME" != "AtmoOmen/DailyRoutines" ]; then
            echo "This is not the AtmoOmen's DailyRoutines repository. Exiting."
            exit 0
          fi
          echo "::set-output name=repo_name::$REPO_NAME"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update total downloads
        run: |
          python Assets/update_downloads.py > Assets/downloads.txt

      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add Assets/downloads.txt
          git commit -m "Update Total Downloads" -a || echo "No changes to commit"
          git push --set-upstream https://github.com/${{ github.repository }} HEAD:main
