name: Update Changelogs

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch release data and update files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          import requests
          import os
          from datetime import datetime

          headers = {
              'Authorization': f"token {os.environ['GITHUB_TOKEN']}",
              'Accept': 'application/vnd.github.v3+json'
          }

          response = requests.get(
              'https://api.github.com/repos/AtmoOmen/DailyRoutines/releases',
              headers=headers
          )
          releases = response.json()
          latest_release = next((r for r in releases if not r['prerelease']), None)

          if latest_release:
              changelog = latest_release['body']
              publish_time = datetime.strptime(latest_release['published_at'], '%Y-%m-%dT%H:%M:%SZ')
              formatted_time = publish_time.strftime('%Y/%m/%d')

              os.makedirs('Assets', exist_ok=True)

              with open('Assets/changelog.txt', 'w', encoding='utf-8') as f:
                  f.write(changelog)

              with open('Assets/changelog_time.txt', 'w') as f:
                  f.write(formatted_time)

              print("Files updated successfully.")
          else:
              print("No non-prerelease version found.")
        shell: python

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Assets/changelog.txt Assets/changelog_time.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update changelog and release time" && git push origin HEAD:main)